### ISSUE TITLE
Run pz-compute using external data 

### ISSUE THREAD

**Issue by gschwend** [linea-it/pz-compute#5]
Run RAIL with external data (not RAIL's simulations)

**Comment by hdante** [comment]
Straightforward estimation with the provided parquet files didn't work: auto-detection in the RAIL package and its dependent libraries require the extension `.pq`, instead of `.parquet`. Creating a set of symbolic links with the appropriate extension worked around the problem. Execution with the developed scripts generated the following results:

- Total: 166 files, 166 slots (threads), 1 file per slot, 3 machines.
- Execution with the flexzboost estimation algorithm.
- Execution with the bpz algorithm didn't work (there's some compatibility problem with the parquet files).
- Machines: apl14, apl12, apl09 (fast machines without slowdown problem).
- Output files configured with 301 bins (301 interpolated points for the estimated probability density functions).
- Input, output and log files placed in the lustre t1 partition.
- 33 files with successful estimation, 133 files failed estimation.
- There were 14.958.539 objects in the 33 successful files.
- Execution time for the 33 successful files: 51:37.
- Average execution time: 6,8 ms/object.
- Summary of file processing time per machine:

```
    Host         min             max                                                        
    10.148.0.31  0:00:08         0:51:30                                                    
    10.148.0.29  0:00:08         0:51:27                                                    
    10.148.0.19  0:00:09         0:51:03                                                    
```
- xgboost error in 12 files: "Check failed: valid: Input data contains \`inf\` or \`nan\`".
- out-of-memory in 121 files: either killed with `SIGKILL` or numpy error: "Unable to allocate 2.45 GiB for an array".
- Memory failure happened when trying to allocate at least 1,42 GiB (the maximum memory request configured by the HTCondor configuration on the Apollo cluster is 2290 MB).
- Files that failed had between 530 MiB and 934 MiB.
- Some examples of results from the successful executions of individual files:
 - object_dpdd_tract3074.pq: 406.285 objects, 21:46 (3,2 ms/object).
 - object_dpdd_tract4636.pq: 229.124 objects, 12:59 (3,4 ms/object).
 - object_dpdd_tract3076.pq: 1.072.853 objects, 49:00 (2,7 ms/object).

**Comment by hdante** [comment]
To be able to fully test the provided data set, while working around the errors, an additional script, `preprocess-parquet.py` (not in repository yet) was written to preprocess the input files, so that both memory errors and invalid input errors were removed (while still keeping all original input data). The script transforms the input files in the following ways:

- only magnitude and error columns are copied from the original files (reduces the number of input columns to 12)
- Limits the maximum number of rows to 100.000, splitting larger files, if necessary
- converts all infinite floating-point values to NaN floating-point values

Preprocessing the original 166 files this way resulted in 1.567 files with at most 100.000 objects each and the estimation process succeeded with all of them. The preprocessing procedure took 4:15 when executed on the Apollo "loginicx" machine. Preprocessing was also done on the lustre t1 partition.

Execution of the estimation procedure gave the following results:
- Total: 1.567 files, 1.567 slots, 1 file per slot, 13 machines, all files succeeded
- Execution time: 18:31, 147 million objects, 5,5 ms/object

**Comment by hdante** [comment]
To better quantify the HTCondor scheduler overhead and reduce the imbalance between different file sizes and machine speeds, a larger execution was made by replicating the DP0 data set. The input data was prepared in the following way:

- 1 copy of the DP0 data set preprocessed with the `preprocess-parquet.py` script with at most 100.000 objects per file (resulting in 1.567 files).
- 20 copies of the DP0 data set preprocessed with the `preprocess-parquet.py` script with at most 400.000 objects per file (resulting in 441 files per copy, 8820 files in 20 copies).
- Total: 10.387 files of up to 42 MiB, 3,1 billion objects, 330 GiB total stored size

Execution in the cluster was done with the `rail-condor` scripts with the same configuration as the previous executions, except that the number of bins were reduced to 31 to avoid any I/O bottlenecks. Results were the following:

- Execution time 4:19:00, 3,6 ms/object, 728 slots, 13 machines
- Individual task execution time and number of tasks per machine:

```
    Host         min             max             tasks
    10.148.0.29  0:00:05         0:19:12         908                                        
    10.148.0.19  0:00:05         0:19:17         919                                        
    10.148.0.32  0:00:05         0:19:13         929                                        
    10.148.0.31  0:00:06         0:19:58         901                                        
    10.148.0.15  0:00:06         0:20:43         885                                        
    10.148.0.16  0:00:06         0:20:10         893                                        
    10.148.0.28  0:00:06         0:19:47         912                                        
    10.148.0.26  0:00:06         0:19:05         921                                        
    10.148.0.18  0:00:06         0:19:16         923                                        
    10.148.0.17  0:00:06         0:18:40         913                                        
    10.148.0.11  0:00:14         0:43:07         429                                        
    10.148.0.12  0:00:14         0:43:59         414                                        
    10.148.0.14  0:00:15         0:43:16         440
```

- 10 fast machines and 3 machines with speed problems (apl01, apl02, apl04, took twice as long with the larger files)
- Total execution of all tasks was not so unbalanced (the scheduler correctly issued more tasks to the faster machines), only a small execution "tail" in the slower machines

**Comment by hdante** [comment]
Besides the larger estimation test, an additional script, [condor-analyze-host-allocation](https://github.com/linea-it/pz-compute/blob/scheduler-scripts/performance/condor/condor-analyze-host-allocation), was created to calculate and plot the resulting dead time caused by the HTCondor scheduler. The plotted image uses different color palettes to indicate full (efficient) allocation of all machine slots, slightly inefficient allocation with a small percentage (<10%) of unallocated slots and inefficient allocation (>= 10%) of unallocated slots. The script parses the condor output log to extract the start and termination times of the individual tasks. An example image with the large DP0 execution follows:

![example-dp0-21copies-condor-apollo.png](https://raw.githubusercontent.com/linea-it/pz-compute/scheduler-scripts/data/example-dp0-21copies-condor-apollo.png)

The chart shows the allocation efficiency on each host (color-coded) through time, in seconds.

Note: the image shows that the fast machines finished their executions in very similar times, while the three slower machines kept running slightly longer (the "tails" on the right side of the chart).

Overall, the inefficiency was mostly bounded, typically at around 20 unallocated slots (< 3% dead time), but at some moments, there were more than 200 unallocated slots (25% dead time). For example, from seconds 2.127 to 2.176, there were more than 200 idle slots for 50 seconds (the log file actually shows a 109 second interval when no new tasks were executed). In principle there's no technical explanation for this level of inefficiency (except a higher priority batch being submitted) and, assuming the generated log timestamps are correct and not skewed, this seems to be simply a deficiency in the HTCondor scheduler's allocation algorithm.
